services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend

    ports:
      - "5500:80"

    depends_on:
      - backend